import Link from 'next/link'
import { createServerSupabase } from '@/lib/supabase/server'
export const dynamic='force-dynamic'
export default async function AlertasPage({searchParams}:{searchParams:{tipo?:string}}){
 const tipo=searchParams.tipo||'todas'; const {data}=await createServerSupabase().from('productos').select('id,nombre,sku,cantidad_stock,stock_minimo,precio,estado_inventario').order('nombre'); const items=data??[]
 const agotados=items.filter(p=>Number(p.cantidad_stock||0)<=0||p.estado_inventario==='agotado'); const minimo=items.filter(p=>Number(p.cantidad_stock||0)>0&&p.stock_minimo!=null&&Number(p.cantidad_stock)<=Number(p.stock_minimo)); const precio=items.filter(p=>!p.precio||Number(p.precio)<=0); const lista=tipo==='agotados'?agotados:tipo==='minimo'?minimo:tipo==='precio'?precio:Array.from(new Map([...agotados,...minimo,...precio].map(p=>[p.id,p])).values())
 return <div className="mx-auto max-w-7xl pb-10"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-lavender-magenta-500">Centro de atención</p><h1 className="mt-1 font-display text-3xl font-bold text-gray-900">Alertas</h1><p className="mt-1 text-sm text-gray-500">Productos que necesitan revisión.</p></div><Link href="/admin" className="text-sm font-bold text-lavender-magenta-700">← Dashboard</Link></div>
 <div className="mt-6 flex flex-wrap gap-2">{[['todas','Todas',lista.length],['agotados','Agotados',agotados.length],['minimo','Bajo mínimo',minimo.length],['precio','Sin precio',precio.length]].map(([v,l,n])=><Link key={String(v)} href={`/admin/alertas?tipo=${v}`} className={`rounded-full px-4 py-2 text-sm font-bold ${tipo===v?'bg-lavender-magenta-700 text-white':'bg-white text-gray-600 ring-1 ring-gray-200'}`}>{l} · {n}</Link>)}</div>
 <div className="mt-6 overflow-hidden rounded-[26px] bg-white shadow-soft-card ring-1 ring-lavender-magenta-100"><div className="grid grid-cols-[1fr_80px_90px_110px] gap-3 border-b border-gray-100 px-5 py-4 text-xs font-bold uppercase tracking-wide text-gray-400"><span>Producto</span><span>Stock</span><span>Mínimo</span><span>Estado</span></div>{lista.length?lista.map(p=><Link href={`/admin/productos/${p.id}`} key={p.id} className="grid grid-cols-[1fr_80px_90px_110px] gap-3 border-b border-gray-50 px-5 py-4 transition last:border-0 hover:bg-lavender-magenta-50"><div className="min-w-0"><p className="truncate text-sm font-bold text-gray-800">{p.nombre}</p><p className="truncate text-xs text-gray-400">{p.sku||'Sin SKU'}</p></div><span className="text-sm font-semibold text-gray-700">{p.cantidad_stock??0}</span><span className="text-sm text-gray-500">{p.stock_minimo??'—'}</span><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${Number(p.cantidad_stock||0)<=0?'bg-red-100 text-red-700':!p.precio?'bg-lavender-magenta-100 text-lavender-magenta-700':'bg-amber-100 text-amber-700'}`}>{Number(p.cantidad_stock||0)<=0?'Agotado':!p.precio?'Sin precio':'Bajo mínimo'}</span></Link>):<div className="p-8 text-center text-sm text-gray-500">✓ No hay alertas en esta categoría.</div>}</div></div>
}
