import Link from 'next/link'
import { createServerSupabase } from '@/lib/supabase/server'
export const dynamic = 'force-dynamic'
const money=(v:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(v)
export default async function ReportesPage(){
 const supabase=createServerSupabase(); const [productos,marcas,categorias]=await Promise.all([
  supabase.from('productos').select('id,nombre,precio,cantidad_stock,estado_inventario,estado_publicacion,oferta,marca_id,categoria_id'),
  supabase.from('marcas').select('id,nombre').order('nombre'), supabase.from('categorias').select('id,nombre').order('nombre')])
 const items=productos.data??[], ms=marcas.data??[], cs=categorias.data??[]; const valor=items.reduce((s,p)=>s+Number(p.precio||0)*Number(p.cantidad_stock||0),0); const unidades=items.reduce((s,p)=>s+Number(p.cantidad_stock||0),0); const agotados=items.filter(p=>p.estado_inventario==='agotado'||Number(p.cantidad_stock||0)<=0).length
 const marcaRows=ms.map(m=>({ ...m,total:items.filter(p=>p.marca_id===m.id).length,unidades:items.filter(p=>p.marca_id===m.id).reduce((s,p)=>s+Number(p.cantidad_stock||0),0)})).sort((a,b)=>b.total-a.total).slice(0,8)
 const catRows=cs.map(c=>({ ...c,total:items.filter(p=>p.categoria_id===c.id).length,unidades:items.filter(p=>p.categoria_id===c.id).reduce((s,p)=>s+Number(p.cantidad_stock||0),0)})).sort((a,b)=>b.total-a.total).slice(0,8)
 return <div className="mx-auto max-w-7xl pb-10"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-lavender-magenta-500">Análisis</p><h1 className="mt-1 font-display text-3xl font-bold text-gray-900">Reportes</h1><p className="mt-1 text-sm text-gray-500">Indicadores del catálogo e inventario actual.</p></div><Link href="/admin" className="text-sm font-bold text-lavender-magenta-700">← Dashboard</Link></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Productos',items.length],['Unidades',unidades],['Publicados',items.filter(p=>p.estado_publicacion==='publicado').length],['En oferta',items.filter(p=>p.oferta).length],['Agotados',agotados]].map(([a,b])=><div key={String(a)} className="rounded-[24px] bg-white p-5 shadow-soft-card ring-1 ring-lavender-magenta-100"><p className="text-xs font-semibold text-gray-500">{a}</p><p className="mt-3 text-3xl font-bold text-lavender-magenta-900">{b}</p></div>)}</div>
 <div className="mt-6 rounded-[26px] bg-gradient-to-br from-lavender-magenta-950 to-lavender-magenta-800 p-6 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-lavender-magenta-200">Valor referencial</p><p className="mt-2 font-display text-4xl font-bold">{money(valor)}</p><p className="mt-1 text-sm text-lavender-magenta-100">Precio de venta × unidades actuales. No es ganancia neta porque el catálogo no registra costo de compra.</p></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-[26px] bg-white p-6 shadow-soft-card ring-1 ring-lavender-magenta-100"><h2 className="text-lg font-bold text-gray-900">Marcas con más productos</h2><div className="mt-4 space-y-2">{marcaRows.map(m=><div key={m.id} className="flex items-center justify-between rounded-2xl bg-gray-50 px-4 py-3"><div><p className="text-sm font-semibold text-gray-800">{m.nombre}</p><p className="text-xs text-gray-400">{m.unidades} unidades</p></div><span className="rounded-full bg-lavender-magenta-50 px-3 py-1 text-xs font-bold text-lavender-magenta-700">{m.total} productos</span></div>)}</div></section><section className="rounded-[26px] bg-white p-6 shadow-soft-card ring-1 ring-lavender-magenta-100"><h2 className="text-lg font-bold text-gray-900">Categorías con más productos</h2><div className="mt-4 space-y-2">{catRows.map(c=><div key={c.id} className="flex items-center justify-between rounded-2xl bg-gray-50 px-4 py-3"><div><p className="text-sm font-semibold text-gray-800">{c.nombre}</p><p className="text-xs text-gray-400">{c.unidades} unidades</p></div><span className="rounded-full bg-lavender-magenta-50 px-3 py-1 text-xs font-bold text-lavender-magenta-700">{c.total} productos</span></div>)}</div></section></div>
 <p className="mt-5 text-xs text-gray-400">Ventas, pedidos y ganancias reales requieren una tabla de pedidos/ventas, que actualmente no existe en este proyecto.</p></div>
}
